steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    
#- task: DotNetCoreCLI@2
#  displayName: 'Build Aporta'
#  inputs:
#    command: 'build'
#    projects: 'src/Aporta.sln'
#    arguments: '--configuration $(buildConfiguration)'
#    versioningScheme: 'byEnvVar'
#    versionEnvVar: 'AssemblyVersion'
    
- task: DotNetCoreCLI@2
  displayName: 'Unit Test Aporta'
  inputs:
    command: 'test'
    nobuild: true
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: CmdLine@2
  displayName: 'Install ReSharper Tools'
  inputs:
    script: 'dotnet tool install -g JetBrains.ReSharper.GlobalTools --arch arm64'

- task: CmdLine@2
  displayName: 'Perform code inspection'
  inputs:
    script: 'jb inspectcode src/Aporta.sln -o=$(Build.ArtifactStagingDirectory)/Resharper.sarif'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: CodeAnalysisLogs
